package wasmcloud:hello;

world hello {
  import wasi:http/outgoing-handler@0.2.2;

  // PART 2: uncomment
  // import wasi:blobstore/blobstore@0.2.0-draft;
  export wasi:http/incoming-handler@0.2.2;
}
